[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "quex-v1-interfaces/=lib/quex-v1-interfaces/",
    "src/=lib/quex-v1-interfaces/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
